### ISSUE TITLE
Can you tell me the training requirements?

### ISSUE THREAD

**Issue by Ylinyuan** [elnino9ykl/WildPASS#3]
Hello, is the segment.py in the segment folder used to train the model? If I want to achieve the effect of the pre-trained model, do I need to use the cityscape and idd datasets? I would like to ask how much GPU memory is needed to do this. Now the GPU is 2080ti and the memory is 11g. Is it impossible to train or will it take a week or a few weeks to train a good model? I would be very grateful if you could answer.

**Comment by elnino9ykl** [comment]
Yes. segment.py is used for training. Mapillary and IDD datasets were used for training. Mapillary and Cityscapes would also work. Two/four 2080ti would be better. You can reduce the batch size or the resolution to facilitate training on a single 1080 GPU. Besides, you can consider our newer trans4pass models for training. https://github.com/jamycheung/Trans4PASS
