### ISSUE TITLE
In Mapillary Vistas dataset, I can not find _gtFine_labelIds.png

### ISSUE THREAD

**Issue by Ylinyuan** [elnino9ykl/WildPASS#4]
Hello, I got an error when running on the Mapillary Vistas dataset because there is no _gtFine_labelIds.png format in it. Does this format require special conversion?I converted the folder format to the required format. I originally thought that the gt in the labels folder was this, but I got an error. Then I modified the code and ran the two CS datasets without reporting an error. So can you tell me which label format it is in the Mapillary Vistas dataset, or how to convert it?
Thanks！

**Comment by elnino9ykl** [comment]
For Mapillary Vistas, one option is to write a small program or script or a Matlab function to convert its annotations to the _gtFine_labelIds format. You can also use CS datasets for your experiments first. Thank you.
